package com.toursim.management.notification;

public enum NotificationCategory {
    ACCOUNT_CREATED,
    BOOKING_RECEIVED,
    BOOKING_STATUS_CHANGED,
    BOOKING_FAILED,
    WAITLIST_JOINED,
    WAITLIST_AVAILABLE,
    WAITLIST_NOTIFIED,
    INQUIRY_RECEIVED,
    INQUIRY_STATUS_CHANGED,
    TRAVELER_PREFERENCES_UPDATED,
    TRIP_REMINDER,
    PAYMENT_RECEIVED,
    PAYMENT_DUE,
    REFUND_PROCESSED,
    ADMIN_ALERT,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    NEWSLETTER_SUBSCRIBED,
}
