package com.toursim.management.notification;

public enum NotificationCategory {
    ACCOUNT_CREATED,
    BOOKING_RECEIVED,
    BOOKING_STATUS_CHANGED,
    WAITLIST_JOINED,
    WAITLIST_AVAILABLE,
    INQUIRY_RECEIVED,
    INQUIRY_STATUS_CHANGED,
    TRAVELER_PREFERENCES_UPDATED,
    PAYMENT_RECEIVED,
    PAYMENT_DUE,
    REFUND_PROCESSED,
    TRIP_REMINDER,
    ADMIN_ALERT,
    BOOKING_FAILED
}
